language: swift
xcode_workspace: AWSAppSyncClient.xcworkspace 
xcode_scheme: AWSAppSync
before_install:
    - pod update
script:
    - xcodebuild -workspace AWSAppSyncClient.xcworkspace -scheme AWSAppSync build
